Repository Remorse-Games/Project-Alphine, pull requests merged in 2020-09, with the labels that each got.

#1 Kejutools/database
  Editor/DatabaseMain.cs
  Scripts/ActorData.cs
Labels: enhancement

#2 Kejutools/database
  Editor/DatabaseMain.cs
Labels: bug

#3 Kejutools general setings/database
  Editor/DatabaseMain.cs
Labels: bug

#4 Kejutools/images
  Editor/DatabaseMain.cs
Labels: enhancement

#5 +Add: Standalone File Browser, opening file inspector in editor
  StandaloneFileBrowser.meta
  StandaloneFileBrowser/IStandaloneFileBrowser.cs
  StandaloneFileBrowser/IStandaloneFileBrowser.cs.meta
  StandaloneFileBrowser/Plugins.meta
  StandaloneFileBrowser/Plugins/Linux.meta
  StandaloneFileBrowser/Plugins/Linux/x86_64.meta
  StandaloneFileBrowser/Plugins/Linux/x86_64/libStandaloneFileBrowser.so
  StandaloneFileBrowser/Plugins/Linux/x86_64/libStandaloneFileBrowser.so.meta
  StandaloneFileBrowser/Plugins/Ookii.Dialogs.dll
  StandaloneFileBrowser/Plugins/Ookii.Dialogs.dll.meta
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.bundle.meta
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.bundle/Contents.meta
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.bundle/Contents/Info.plist
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.bundle/Contents/Info.plist.meta
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.bundle/Contents/MacOS.meta
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.bundle/Contents/MacOS/StandaloneFileBrowser
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.bundle/Contents/MacOS/StandaloneFileBrowser.meta
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.jslib
  StandaloneFileBrowser/Plugins/StandaloneFileBrowser.jslib.meta
  StandaloneFileBrowser/Plugins/System.Windows.Forms.dll
  StandaloneFileBrowser/Plugins/System.Windows.Forms.dll.meta
  StandaloneFileBrowser/StandaloneFileBrowser.cs
  StandaloneFileBrowser/StandaloneFileBrowser.cs.meta
  StandaloneFileBrowser/StandaloneFileBrowserEditor.cs
  StandaloneFileBrowser/StandaloneFileBrowserEditor.cs.meta
  StandaloneFileBrowser/StandaloneFileBrowserLinux.cs
  StandaloneFileBrowser/StandaloneFileBrowserLinux.cs.meta
  StandaloneFileBrowser/StandaloneFileBrowserMac.cs
  StandaloneFileBrowser/StandaloneFileBrowserMac.cs.meta
  StandaloneFileBrowser/StandaloneFileBrowserWindows.cs
  StandaloneFileBrowser/StandaloneFileBrowserWindows.cs.meta
Labels: enhancement

#6 - Modified, DatabaseMain.cs, Added initial equipment, traits, and notes tab
  Editor/DatabaseMain.cs
Labels: enhancement

#9 -Modified: ActorTab.cs, Added Skin for light mode, remove temp vars, and added safety for images
  Editor/ActorTab.cs
Labels: enhancement

#10 - Modified : Readme.txt , Add Init Commit
  Readme.txt
Labels: documentation

#11 Ziven/database
  First.unity
  First.unity.meta
  Scripts/PlayerMovement.cs
Labels: enhancement

#12 +Add: ExpWindow, to view and modify exp parameter of a class
  Editor/ActorTab.cs
  Editor/ClassExpWindow.cs
  Editor/ClassTab.cs
  Editor/DatabaseMain.cs
  Scripts/ClassesData.cs
Labels: enhancement

#16 - Modified: SkillTab.cs
  Editor/SkillsTab.cs
Labels: enhancement

#17 -Modified: ParameterCurveWindow.cs Edited MDefenseCurve Color
  Editor/ParameterCurveWindow.cs
Labels: bug

#19 - Modified: DatabaseMain.cs SkillsTab.cs SkillData.cs
  Editor/DatabaseMain.cs
  Editor/SkillsTab.cs
  Scripts/SkillData.cs
Labels: enhancement

#20 - Modified: SkillsTab.cs SkillData.cs
  Editor/BaseTab.cs
  Editor/SkillsTab.cs
  Scripts/SkillData.cs
Labels: enhancement
